from typing import TypedDict, Optional

class GraphState(TypedDict):
    """
    Represents the state of the Hybrid Graph-RAG compliance pipeline.
    
    # TODO: Core State Management
    # 1. Ensure all fields are properly updated by their respective nodes.
    # 2. If expanding the pipeline, add new state keys here (e.g., 'user_metadata').
    """
    
    question: str
    """The raw compliance or legal query submitted by the user."""
    
    vector_context: str
    """Relevant legal text chunks retrieved from the Qdrant Vector database."""
    
    graph_context: str
    """Structural law relationships and cross-references fetched from Neo4j."""
    
    final_answer: str
    """The synthesized response generated by the Gemini LLM."""
    
    error_message: Optional[str]
    """Captured runtime exceptions to prevent the state machine from crashing."""